import logging
import pymongo
import pymongo.collection
from typing import Dict
from datetime import datetime
import functools
from pathlib import PurePath
import sys
import logging
logger = logging.getLogger()

import iwst as namespacepackage
NAMESPACEPACKAGES = [path for path in namespacepackage.__spec__.submodule_search_locations]  # used to filter the log generated by the package only


def retry_connection(func):
    @functools.wraps(func)  
    def wrapper(self, *args, **kwargs):
        try:
            self.client.is_mongos
            isconnected = True
        except pymongo.errors.ServerSelectionTimeoutError as _:
            logger.debug(f"Failed to log to database. Reconnecting.")
            self.client.close()
        if not isconnected:
            self.client = self._connect()
        return func(self, *args, **kwargs)
    return wrapper


class MongoFormatter(logging.Formatter):

    def format(self, record):
        """Formats LogRecord into python dictionary.
        
        `record` may have the `current_user` if it provided as an extra arg to the logger message.

        """
        try:
            user = record.current_user
        except AttributeError:           
            user = 'root'
        
        log = {
            'user': user,
            'creation time': datetime.today(),
            'level': record.levelname,
            'message': record.getMessage(),
            'module': record.module,
            'method': record.funcName,
            'lineNumber': record.lineno
        }

        return log


class MongoHandler(logging.Handler):

    _CAPPED_SIZE = 100000  # bytes
    _CAPPED_MAX = 10000  # documents
    _COLLECTION_NAME = 'logs'
    _BASE_LEVEL = 'INFO'
    _TIMEOUT = 5000

    def __init__(self, host: str, port: int, dbname: str):
        """Set up handler for MongoDB"""
        logging.Handler.__init__(self, self._BASE_LEVEL)
        
        self.host = host
        self.port = port
        self.dbname = dbname
        self.client = self._connect()
        
        # test connection
        try:
            self.client.is_mongos
            logger.info(f'Connected to database.')
        except pymongo.errors.ServerSelectionTimeoutError as err:
            logger.error(f"Failed to connect to database. Check the VPN connection or the MongoDB service. \n({err})")
            sys.exit(1)

        # retrieve main database
        database = self.client[dbname]

        # create or get collection for logs
        try:
            self.collection = pymongo.collection.Collection(
                database, 
                self._COLLECTION_NAME,
                capped=True, 
                max=self._CAPPED_MAX,
                size=self._CAPPED_SIZE
            )
        except pymongo.errors.OperationFailure:
            self.collection = database[self._COLLECTION_NAME]
    
    def _connect(self) -> pymongo.MongoClient:
        """Connect to mongodb"""
        client = pymongo.MongoClient(
            host=self.host, 
            port=self.port, 
            serverSelectionTimeoutMS=self._TIMEOUT
        )
        return client

    @retry_connection
    def emit(self, record: Dict[str, str]):
        """Inserting new logging record to mongo database"""
        # check if the log comes from the namespace package
        logsource = PurePath(record.pathname)
        checks = [logsource.is_relative_to(path) for path in NAMESPACEPACKAGES]
        
        # store log
        if True in checks:
            try:
                self.collection.insert_one(self.format(record))
            except pymongo.errors.ServerSelectionTimeoutError as _:
                pass